services:
  sgr:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: sgr-deep-research
    restart: unless-stopped

    ports:
      - "8010:8010"
    volumes:
      - ./src:/app  
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

