name: Lint

on:
  - pull_request
  - workflow_call

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install pre-commit

      - name: Lint
        run: make format
